services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: proyecto1-web:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
